// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqBCfnrgK2WWYaHz8BU0KUqmYZIGG1Xxs',
    appId: '1:801779467180:web:2ea3e1d2158c841eaa3009',
    messagingSenderId: '801779467180',
    projectId: 'quranuna-1924-623d4',
    authDomain: 'quranuna-1924-623d4.firebaseapp.com',
    storageBucket: 'quranuna-1924-623d4.firebasestorage.app',
    measurementId: 'G-8L01YSFPYP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFpnrVq1EimSS1YybR8PoNlGtwvNGYuow',
    appId: '1:801779467180:android:4c954848f7d75d36aa3009',
    messagingSenderId: '801779467180',
    projectId: 'quranuna-1924-623d4',
    storageBucket: 'quranuna-1924-623d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQtOYp_yHYTUVpkQZxz1tNDvlBzBbuMuc',
    appId: '1:801779467180:ios:08850c6790fbc709aa3009',
    messagingSenderId: '801779467180',
    projectId: 'quranuna-1924-623d4',
    storageBucket: 'quranuna-1924-623d4.firebasestorage.app',
    androidClientId: '801779467180-joph7k7tdpocu3an9cmti59qu94vhlrf.apps.googleusercontent.com',
    iosClientId: '801779467180-p83tdkqva6su4p998vcv2d42pmv1ef6n.apps.googleusercontent.com',
    iosBundleId: 'com.assyfa.quranapp',
  );
}
