// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKrzPKZY08PZaDSTQxI_gXfZO3rbk35Vw',
    appId: '1:319156609776:web:54b7536a03356248455835',
    messagingSenderId: '319156609776',
    projectId: 'quranuna-995dc',
    authDomain: 'quranuna-995dc.firebaseapp.com',
    storageBucket: 'quranuna-995dc.firebasestorage.app',
    measurementId: 'G-TB3G1EPXE5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsC655ytDJ3_Fh47zELPaifp8edgtN7y8',
    appId: '1:319156609776:android:2c2f3afdab9902ba455835',
    messagingSenderId: '319156609776',
    projectId: 'quranuna-995dc',
    storageBucket: 'quranuna-995dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATbRa3XiCeBpb7FBTA4xUe7Bmabx89VEc',
    appId: '1:319156609776:ios:ebfdb22e015eefb4455835',
    messagingSenderId: '319156609776',
    projectId: 'quranuna-995dc',
    storageBucket: 'quranuna-995dc.firebasestorage.app',
    iosBundleId: 'com.example.quranApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATbRa3XiCeBpb7FBTA4xUe7Bmabx89VEc',
    appId: '1:319156609776:ios:ebfdb22e015eefb4455835',
    messagingSenderId: '319156609776',
    projectId: 'quranuna-995dc',
    storageBucket: 'quranuna-995dc.firebasestorage.app',
    iosBundleId: 'com.example.quranApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKrzPKZY08PZaDSTQxI_gXfZO3rbk35Vw',
    appId: '1:319156609776:web:681143ac3fef12e5455835',
    messagingSenderId: '319156609776',
    projectId: 'quranuna-995dc',
    authDomain: 'quranuna-995dc.firebaseapp.com',
    storageBucket: 'quranuna-995dc.firebasestorage.app',
    measurementId: 'G-Q9MH4JLVG3',
  );
}
